### ISSUE TITLE
[BUG]https://paste.atlauncher.com/view/4265c9fb-c10f-4006-a239-49941d9406f8

### ISSUE THREAD

**Issue by davisharleyr** [AMPZNetwork/All-The-Forge-10#18] opened 2024-05-07 14:56 UTC
## Bug Description
Please provide a concise description of the issue you're experiencing.
 My game keeps crashing before I even get it launched. I have re-installed twice now and the issue still persists. 
## Reproduction Steps
To replicate the problem, follow these steps:
1. Navigate to '...'
4. Observe the error

## Expected Outcome
Explain what you anticipated should happen in detail.

## Crash Log (if applicable)
If the bug triggers a crash, please include or link the crash log here.

## Screenshots
If relevant, include screenshots to aid in explaining the issue.

## Basic Information (please fill in the following details):
 - Operating System: [e.g., Windows]
 - All The Forge Version: [e.g., 5.4]
 - Platform: [e.g., atlauncher]
 - Additional Mods Installed: [e.g., Optifine]

**Comment by LabsZero** [comment] 2024-05-07 14:58
Delete the mods, and config folders then do a reinstall

**Comment by burdoto** [comment] 2024-05-07 15:01
duplicate of #17

**Closed as not planned by burdoto** 2024-05-07 15:01 UTC
Labels: Bug
